[versions]
agp = "9.3.1"
kotlin = "2.3.21"
mavenPublish = "0.36.0"
coroutines = "1.11.0"
serializationJson = "1.11.0"
okio = "3.18.1"
skiko = "0.148.2"
wire = "6.4.5"

[libraries]
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "coroutines" }
kotlinx-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serializationJson" }
okio = { module = "com.squareup.okio:okio", version.ref = "okio" }
okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "okio" }
skiko = { module = "org.jetbrains.skiko:skiko", version.ref = "skiko" }
wire-runtime = { module = "com.squareup.wire:wire-runtime", version.ref = "wire" }

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
android-kotlin-multiplatform-library = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
maven-publish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
wire = { id = "com.squareup.wire", version.ref = "wire" }
